server:
  port: 8001

spring:
  application:
    name: academy-edu

  profiles:
    active: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/academy_edu?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 6000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: AcademyHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.th.academy.edu.pojo
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: warn
